title: My Website
description: Personal website of Natesh B V
theme: jekyll-theme-cayman

# Navigation links
nav:
  - title: Home
    url: /index.md
  - title: About
    url: /About.md
  - title: Research
    url: /Research.md
  - title: Courses
    url: /Courses.md
  - title: Project
    url: /Project.md
  - title: Publications
    url: /Publications.md
  - title: Services
    url: /Services.md
  - title: Contact
    url: /Contact.md

