title: Dr. Natesh B V
description: Personal website of Dr. Natesh B V – Academic, Researcher, and Educator
url: https://username.github.io   # replace with your GitHub Pages URL
theme: jekyll-theme-cayman

# Navigation links
nav:
  - title: Home
    url: /
  - title: About
    url: /about.html
  - title: Research
    url: /research.html
  - title: Courses
    url: /courses.html
  - title: Projects
    url: /projects.html
  - title: Publications
    url: /publications.html
  - title: Services
    url: /services.html
  - title: Contact
    url: /contact.html

# Plugins for SEO
plugins:
  - jekyll-sitemap
