# title: Welcome.... to My Website...!!
description: Personal website of Natesh B V
theme: jekyll-theme-cayman

# Navigation links
nav:
  - title: Home
    url: /index.html
  - title: About
    url: /About.html
  - title: Research
    url: /Research.html
  - title: Courses
    url: /Courses.html
  - title: Projects
    url: /Projects.html
  - title: Publications
    url: /Publications.html
  - title: Services
    url: /Services.html
  - title: Contact
    url: /Contact.html

